### PR TITLE
[ADD] a few features

### PR DESCRIPTION
**Pull request by hbrunn**
this adds opening the group's record, allowing to set a start date and a standard scale, and a small refactoring so that inheriting views can easily manipulate the popup's context.

### CODE REVIEW

**Comment by sbidoul** [comment]
@adrienpeiffer

**Comment by lmignon** [comment]
Thank you @hbrunn. The code LGTM 
 ping @adrienpeiffer

**Comment by adrienpeiffer** [comment]
Thanks @hbrunn ! I test this one tommorow

**Comment by adrienpeiffer** [comment]
:+1: Good !

**Pull request merged**
